/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.EstudiantesController;
import controller.LocacionesController;
import javax.swing.ImageIcon;
import model.vo.LocacionVo;

/**
 *
 * @author David Rojas, Julián Rodríguez
 */
public class verLocacionU extends javax.swing.JFrame {

    LocacionesController loCon;
    LocacionVo loc;
    EstudiantesController esCon;
    String idE;
    String nombre;
    /**
     * Creates new form verLocacionU
     */
    public verLocacionU() {
        initComponents();
        locacion.setVisible(false);
        nEs.setVisible(false);
        ruta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        enviarSolicitud = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estudiante2 = new javax.swing.JLabel();
        extra = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        denunciar = new javax.swing.JButton();
        valorar = new javax.swing.JButton();
        locacion = new javax.swing.JLabel();
        nEs = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        ruta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detalles = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        direccion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Dirección:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Ver Locación");

        salir.setBackground(new java.awt.Color(255, 0, 0));
        salir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        enviarSolicitud.setBackground(new java.awt.Color(204, 204, 255));
        enviarSolicitud.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enviarSolicitud.setForeground(new java.awt.Color(0, 0, 51));
        enviarSolicitud.setText("Enviar Solicitud");
        enviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarSolicitudActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Detalles:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Precio:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Indicaciones:");

        estudiante2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estudiante2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/logoroomuis_mini.png"))); // NOI18N

        extra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        extra.setText("EXTRA");

        precio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precio.setText("PRECIO");

        denunciar.setBackground(new java.awt.Color(255, 51, 51));
        denunciar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        denunciar.setForeground(new java.awt.Color(255, 255, 255));
        denunciar.setText("Denunciar");
        denunciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denunciarActionPerformed(evt);
            }
        });

        valorar.setBackground(new java.awt.Color(0, 204, 51));
        valorar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valorar.setForeground(new java.awt.Color(51, 0, 0));
        valorar.setText("Valorar");
        valorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorarActionPerformed(evt);
            }
        });

        locacion.setText("id loc");

        nEs.setText("nombre es");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Imagen:");

        ruta.setText("ruta");

        detalles.setEditable(false);
        detalles.setColumns(20);
        detalles.setRows(5);
        jScrollPane1.setViewportView(detalles);

        direccion.setEditable(false);
        direccion.setColumns(20);
        direccion.setRows(5);
        jScrollPane2.setViewportView(direccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(731, 731, 731)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(extra, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(salir)
                        .addGap(38, 38, 38)
                        .addComponent(enviarSolicitud)
                        .addGap(31, 31, 31)
                        .addComponent(valorar)
                        .addGap(35, 35, 35)
                        .addComponent(denunciar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(locacion)
                        .addGap(170, 170, 170)
                        .addComponent(nEs)
                        .addGap(56, 56, 56)
                        .addComponent(ruta)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estudiante2)
                        .addGap(131, 131, 131))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locacion)
                            .addComponent(nEs)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(ruta)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)
                        .addGap(121, 121, 121)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(estudiante2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(extra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precio)
                        .addGap(184, 184, 184))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salir)
                            .addComponent(enviarSolicitud)
                            .addComponent(valorar)
                            .addComponent(denunciar))
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void enviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarSolicitudActionPerformed
        SolicitudCompra sc = new SolicitudCompra();
        sc.setLocationRelativeTo(null);
        sc.setId(locacion.getText());
        sc.setIdE(nEs.getText());
        sc.setVisible(true);
        dispose();
    }//GEN-LAST:event_enviarSolicitudActionPerformed

    private void denunciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denunciarActionPerformed
        Denuncia de = new Denuncia();
        de.setLocationRelativeTo(null);
        de.setId(locacion.getText());
        de.setIdE(nEs.getText());
        de.setVisible(true);
    }//GEN-LAST:event_denunciarActionPerformed

    private void valorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorarActionPerformed
        Valoracion va = new Valoracion();
        va.setLocationRelativeTo(null);
        va.setId(locacion.getText(),2);
        va.setIdE(idEst);
        va.setVisible(true);
        dispose();
    }//GEN-LAST:event_valorarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verLocacionU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verLocacionU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verLocacionU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verLocacionU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verLocacionU().setVisible(true);
            }
        });
    }

     public void setControllerLoc(LocacionesController loCon) {
        this.loCon = loCon;
    }
     int idEst;
     public void setConEstudiante(EstudiantesController esCon) {
        this.esCon = esCon;
        idEst = esCon.getIdE();
        
    }
     
    public void setLoc(LocacionVo loc) {
        this.loc = loc;
        locacion.setText(loc.getDireccion());
        direccion.setText(loc.getDireccion());
        extra.setText(loc.getExtraDir());
        precio.setText(String.valueOf(loc.getPrecio()));
        detalles.setText(loc.getDetalles());
        ruta.setText(loc.getImagen());
        imagen.setIcon(new ImageIcon(ruta.getText()));
    }
    
    
    public void setIdNE(String nombre) {
        this.nombre = nombre;
        nEs.setText(nombre);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton denunciar;
    private javax.swing.JTextArea detalles;
    private javax.swing.JTextArea direccion;
    private javax.swing.JButton enviarSolicitud;
    private javax.swing.JLabel estudiante2;
    private javax.swing.JLabel extra;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel locacion;
    private javax.swing.JLabel nEs;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel ruta;
    private javax.swing.JButton salir;
    private javax.swing.JButton valorar;
    // End of variables declaration//GEN-END:variables
}
